### ISSUE TITLE
Usar Stream no listar_rec

### ISSUE THREAD

**Issue by nirev** [ramalho/alef#5]
https://hexdocs.pm/elixir/IO.html#stream/2

https://github.com/ramalho/alef/blob/master/passos/3/alef/lib/alef.ex#L34

Poderia usar Stream de linhas, mapear para o analisar linha e filtrar quem pertence ao MapSet

**Comment by ramalho** [comment]
Muito grato, @nirev ficou mais sucinto, elegante e provavelmente mais eficiente!
